language: node_js
node_js:
  - "4"
  - "5"
  - "stable"

services:
  - redis-server

env:
- REDIS_PORT_6379_TCP_ADDR=localhost

before_script:
  - npm run lint

after_script:
  - npm run coverage
  - npm run update-coveralls
  - npm run check-coverage

notifications:
  email:
    on_success: never
    on_failure: change
